---
swagger: "2.0"
info:
  version: "2016-04-15T16:51:33Z"
  title: "CaesarCalcAPI2"
host: "a0p25chmzl.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Input"
        required: true
        schema:
          $ref: "#/definitions/Input"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Success"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/Error"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Allow-Origin-Header:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          'Bad Request: .*':
            statusCode: "400"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\n{\n  \"error\"\
                \ : \"$inputRoot.errorMessage\"\n}"
          .*:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\n{\n  \"decimal\"\
                \ : $inputRoot.decimal,\n  \"roman\" : \"$inputRoot.roman\"\n}"
        requestTemplates:
          application/json: "#set($inputRoot = $input.path('$'))\n{\n  \"value\":\
            \ \"$inputRoot.value\"\n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:618006114477:function:CaescarCalcLambda2/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
definitions:
  Input:
    type: "object"
    required:
    - "value"
    properties:
      value:
        type: "string"
  Empty:
    type: "object"
  Error:
    type: "object"
    properties:
      error:
        type: "string"
  Success:
    type: "object"
    properties:
      decimal:
        type: "integer"
      roman:
        type: "string"